# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f62395f7b57f113c74e7ccf29678f21ba79104eedf665f3671549cb67c5a0d9c1910779fa9dfcf74ad12bc4eb4c0bbc1cae279bb983061e74787ee61d3fb26e5

test:
  secret_key_base: fc18477a038e792efbe8c84b55e5d52d55da9f93857eeb6d2ad5657def3c7008970a35589fcdb2e1fce2e9130609df01f763dff5a0b4cf4a703087db076d7777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
